blueprint:
  custom_cards:
  - mushroom-media-player-card
  description: replaces media player card with mushroom media player card by Bourner
  name: Replace Mushroom Media Player Card
  input: 
    info:
      type: checkbox
      description: Use Media Info
    art:
      type: checkbox
      description: Use Media Artwork
    collapsible:
      type: checkbox
      description: Collapse Controls when off     
  type: replace-card
  version: '1.2'
card:
  type: custom:mushroom-media-player-card
  use_media_info: $info$
  use_media_artwork: $art$
  collapsible_controls: $collapsible$
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  volume_controls:
    - volume_mute
    - volume_buttons
    - volume_set
  media_controls:  
    - on_off
    - shuffle
    - previous
    - play_pause_stop
    - next
    - repeat
