blueprint:
  custom_cards:
  - mushroom-cover-card
  description: replaces cover card with mushroom cover card by Bourner
  name: Replace Mushroom Cover Card
  input:
    state:
      type: checkbox
      descripion: Hide State
    button:
      type: checkbox
      descripion: Show Button Controls
    position:
      type: checkbox
      descripion: Show Position Controls     
  type: replace-card
  version: '1.2'
card:
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  hide_state: $state$
  show_buttons_control: $button$
  show_position_control: $position$
  type: custom:mushroom-cover-card
