blueprint:
  custom_cards:
  - mushroom-light-card
  description: replaces light card with mushroom light card by Bourner
  input:
    name: null
  name: Replace Mushroom Light Card
  type: card
  version: '1.0'
card:
  entity: $replace_with_input_entity$
  hide_state: false
  show_brightness_control: true
  show_color_control: true
  show_color_temp_control: true
  type: custom:mushroom-light-card
  use_light_color: true
