blueprint:
  custom_cards:
  - mushroom-entity-card
  description: replaces entity card with mushroom entity card by Bourner
  input:
    name: null
  name: Replace Mushroom Entity Card
  type: card
  version: '1.0'
card:
  entity: $replace_with_input_entity$
  type: custom:mushroom-entity-card
