blueprint:
  custom_cards:
  - button-card
  description: Homekit Infused Light Card Blueprint by Bourner
  input:
    button_entity:
      description: This is the button entity
      name: Button entity
    button_name:
      description: This is the button name
      name: Button name
  name: Homekit Infused Light Card
  type: card
  version: '1.0'
card:
  entity: $button_entity$
  label: $button_name$
  template:
  - light
  - icon_hue
  type: custom:button-card
