blueprint:
  custom_cards:
  - button-card
  - bar-card
  - vertical-stack-in-card
  description: Docker card by Bourner
  input:
    docker_name:
      description: 'This is the Docker Container #1'
      name: 'Select docker container #1'
      type: text-field
    docker_name2:
      description: 'This is the Docker Container #2'
      name: 'Select docker container #2'
      type: text-field
    docker_name3:
      description: 'This is the Docker Container #3'
      name: 'Select docker container #3'
      type: text-field
    docker_name4:
      description: 'This is the Docker Container #4'
      name: 'Select docker container #4'
      type: text-field
    docker_name5:
      description: 'This is the Docker Container #5'
      name: 'Select docker container #5'
      type: text-field
    docker_name6:
      description: 'This is the Docker Container #6'
      name: 'Select docker container #6'
      type: text-field
    docker_title:
      description: 'This is the title of Docker Container #1'
      name: 'Select docker title #1'
      type: text-field
    docker_title2:
      description: 'This is the title of Docker Container #2'
      name: 'Select docker title #2'
      type: text-field
    docker_title3:
      description: 'This is the title of Docker Container #3'
      name: 'Select docker title #3'
      type: text-field
    docker_title4:
      description: 'This is the title of Docker Container #4'
      name: 'Select docker title #4'
      type: text-field
    docker_title5:
      description: 'This is the title of Docker Container #5'
      name: 'Select docker title #5'
      type: text-field
    docker_title6:
      description: 'This is the title of Docker Container #6'
      name: 'Select docker title #6'
      type: text-field
    docker_url:
      description: 'This is your docker URL #6'
      name: 'Select docker URL #6'
      type: text-field
  name: Docker card Blueprint
  type: page
  version: 1
card:
  cards:
  - cards:
    - cards:
      - cards:
        - content: <ha-icon icon="si:portainer"></ha-icon>
          style: "ha-card { box-shadow: none; \nbackground-color: var(--dwains-theme-primary);\n\
            --mdc-icon-size: 128px; \ncolor: var(--primary-color)        \n}\nha-markdown\
            \ { padding-bottom: 1px !important; }\n"
          type: markdown
        - color: var(--primary-color)
          icon: mdi:docker
          name: Portainer
          show_state: false
          styles:
            card:
            - background-color: var(--dwains-theme-primary)
            - box-shadow: none
            - width: 250px
            grid:
            - grid-template-areas: '"i n" "i n" "i n"'
            - grid-template-columns: 25% 75%
            - grid-template-rows: min-content min-content
            name:
            - font-size: 15px
            - font-weight: bold
          tap_action:
            action: url
            url_path: $docker_url$
          type: custom:button-card
        type: vertical-stack
      - cards:
        - content: Docker
          style: "ha-card { box-shadow: none; \nbackground-color: var(--dwains-theme-primary);}\n\
            ha-markdown { padding-bottom: 1px !important; }        \n"
          type: markdown
        - entities:
          - animation:
              state: 'on'
            color: var(--primary-color) !important;
            entity: sensor.docker_containers_total
            entity_row: true
            height: 15px
            icon: mdi:counter
            name: Containers Total
            positions:
              icon: outside
              indicator: inside
              name: outside
              value: outside
            style: "ha-icon {\n  margin-top: -7px;\n  color: var(--primary-color)\
              \ !important;\n  padding-right: 5px;\n}      \n"
            type: custom:bar-card
            width: 70%
          - animation:
              state: 'on'
            color: var(--primary-color) !important;
            entity: sensor.docker_containers_running
            entity_row: true
            height: 15px
            icon: mdi:play
            name: Containers Running
            positions:
              icon: outside
              indicator: inside
              name: outside
              value: outside
            style: "ha-icon\t {\n  margin-top: -7px;\n  color: var(--primary-color)\
              \ !important;\n  padding-right: 5px;\n}\n"
            type: custom:bar-card
            width: 70%
          - animation:
              state: 'on'
            color: var(--primary-color) !important;
            entity: sensor.docker_containers_paused
            entity_row: true
            height: 15px
            icon: mdi:pause
            name: Containers Paused
            positions:
              icon: outside
              indicator: inside
              name: outside
              value: outside
            style: "ha-icon\t {\n  margin-top: -7px;\n  color: var(--primary-color)\
              \ !important;\n  padding-right: 5px;\n}        \n"
            type: custom:bar-card
            width: 70%
          - animation:
              state: 'on'
            color: var(--primary-color) !important;
            entity: sensor.docker_containers_stopped
            entity_row: true
            height: 15px
            icon: mdi:stop
            name: Containers Stopped
            positions:
              icon: outside
              indicator: inside
              name: outside
              value: outside
            style: "ha-icon\t {\n  margin-top: -7px;\n  color: var(--primary-color)\
              \ !important;\n  padding-right: 5px;\n}\t\t\t\n"
            type: custom:bar-card
            width: 70%
          style: "ha-card { box-shadow: none;\nbackground-color: var(--dwains-theme-primary);\
            \ }\t\t   \n"
          type: entities
        type: vertical-stack
      items_classes: col-xs-12 col-md-12 col-lg-6 col-xl-6
      type: custom:dwains-flexbox-card
    type: custom:vertical-stack-in-card
  - cards:
    - cards:
      - entities:
        - entity: sensor.docker_$docker_name$_cpu
          name: CPU use
        - entity: sensor.docker_$docker_name$_memory
          name: Memory use
        - entity: sensor.docker_$docker_name$_network_total_down
          name: Down link
        - entity: sensor.docker_$docker_name$_network_total_up
          name: Up link
        - entity: sensor.docker_$docker_name$_status
          name: Status
        - entity: sensor.docker_$docker_name$_up_time
          name: Uptime
        style: ":host {\n  --paper-item-icon-color: var(--primary-color) !important;\n\
          }\nha-icon {\n  margin-top: -7px;\n  color: var(--primary-color) !important;\n\
          \  padding-right: 5px;\n}\n.card-header {\n  padding: 5px 16px;\n  font-size:\
          \ 18px;\n  font-weight: 700 !important;\n}\n.card-content div {\n    margin:\
          \ 0 !important;\n}\n#states {\n  padding-top: 0px !important;\n  padding-bottom:\
          \ 0px !important;\n}\t  \t  \n"
        title: $docker_title$
        type: entities
      type: vertical-stack
    - cards:
      - entities:
        - entity: sensor.docker_$docker_name2$_cpu
          name: CPU use
        - entity: sensor.docker_$docker_name2$_memory
          name: Memory use
        - entity: sensor.docker_$docker_name2$_network_total_down
          name: Down link
        - entity: sensor.docker_$docker_name2$_network_total_up
          name: Up link
        - entity: sensor.docker_$docker_name2$_status
          name: Status
        - entity: sensor.docker_$docker_name2$_up_time
          name: Uptime
        style: ":host {\n  --paper-item-icon-color: var(--primary-color) !important;\n\
          }\nha-icon {\n  margin-top: -7px;\n  color: var(--primary-color) !important;\n\
          \  padding-right: 5px;\n}\n.card-header {\n  padding: 5px 16px;\n  font-size:\
          \ 18px;\n  font-weight: 700 !important;\n}\n.card-content div {\n    margin:\
          \ 0 !important;\n}\n#states {\n  padding-top: 0px !important;\n  padding-bottom:\
          \ 0px !important;\n}\t\t  \t  \n"
        title: $docker_title2$
        type: entities
      type: vertical-stack
    - cards:
      - entities:
        - entity: sensor.docker_$docker_name3$_cpu
          name: CPU use
        - entity: sensor.docker_$docker_name3$_memory
          name: Memory use
        - entity: sensor.docker_$docker_name3$_network_total_down
          name: Down link
        - entity: sensor.docker_$docker_name3$_network_total_up
          name: Up link
        - entity: sensor.docker_$docker_name3$_status
          name: Status
        - entity: sensor.docker_$docker_name3$_up_time
          name: Uptime
        style: ":host {\n  --paper-item-icon-color: var(--primary-color) !important;\n\
          }\nha-icon {\n  margin-top: -7px;\n  color: var(--primary-color) !important;\n\
          \  padding-right: 5px;\n}\n.card-header {\n  padding: 5px 16px;\n  font-size:\
          \ 18px;\n  font-weight: 700 !important;\n}\n.card-content div {\n    margin:\
          \ 0 !important;\n}\n#states {\n  padding-top: 0px !important;\n  padding-bottom:\
          \ 0px !important;\n}\t\t  \t  \n"
        title: $docker_title3$
        type: entities
      type: vertical-stack
    - cards:
      - entities:
        - entity: sensor.docker_$docker_name4$_cpu
          name: CPU use
        - entity: sensor.docker_$docker_name4$_memory
          name: Memory use
        - entity: sensor.docker_$docker_name4$_network_total_down
          name: Down link
        - entity: sensor.docker_$docker_name4$_network_total_up
          name: Up link
        - entity: sensor.docker_$docker_name4$_status
          name: Status
        - entity: sensor.docker_$docker_name4$_up_time
          name: Uptime
        style: ":host {\n  --paper-item-icon-color: var(--primary-color) !important;\n\
          }\nha-icon {\n  margin-top: -7px;\n  color: var(--primary-color) !important;\n\
          \  padding-right: 5px;\n}\n.card-header {\n  padding: 5px 16px;\n  font-size:\
          \ 18px;\n  font-weight: 700 !important;\n}\n.card-content div {\n    margin:\
          \ 0 !important;\n}\n#states {\n  padding-top: 0px !important;\n  padding-bottom:\
          \ 0px !important;\n}\t\t  \n"
        title: $docker_title4$
        type: entities
      type: vertical-stack
    - cards:
      - entities:
        - entity: sensor.docker_$docker_name5$_cpu
          name: CPU use
        - entity: sensor.docker_$docker_name5$_memory
          name: Memory use
        - entity: sensor.docker_$docker_name5$_network_total_down
          name: Down link
        - entity: sensor.docker_$docker_name5$_network_total_up
          name: Up link
        - entity: sensor.docker_$docker_name5$_status
          name: Status
        - entity: sensor.docker_$docker_name5$_up_time
          name: Uptime
        style: ":host {\n  --paper-item-icon-color: var(--primary-color) !important;\n\
          }\t\t\nha-icon {\n  margin-top: -7px;\n  color: var(--primary-color) !important;\n\
          \  padding-right: 5px;\n}\n.card-header {\n  padding: 5px 16px;\n  font-size:\
          \ 18px;\n  font-weight: 700 !important;\n}\n.card-content div {\n    margin:\
          \ 0 !important;\n}\t\t  \n#states {\n  padding-top: 0px !important;\n  padding-bottom:\
          \ 0px !important;\n}\n"
        title: $docker_title5$
        type: entities
      type: vertical-stack
    - cards:
      - entities:
        - entity: sensor.docker_$docker_name6$_cpu
          name: CPU use
        - entity: sensor.docker_$docker_name6$_memory
          name: Memory use
        - entity: sensor.docker_$docker_name6$_network_total_down
          name: Down link
        - entity: sensor.docker_$docker_name6$_network_total_up
          name: Up link
        - entity: sensor.docker_$docker_name6$_status
          name: Status
        - entity: sensor.docker_$docker_name6$_up_time
          name: Uptime
        style: ":host {\n  --paper-item-icon-color: var(--primary-color) !important;\n\
          }\t\t\nha-icon {\n  margin-top: -7px;\n  color: var(--primary-color) !important;\n\
          \  padding-right: 5px;\n}\n.card-header {\n  padding: 5px 16px;\n  font-size:\
          \ 18px;\n  font-weight: 700 !important;\n}\n.card-content div {\n    margin:\
          \ 0 !important;\n}\t\t  \n#states {\n  padding-top: 0px !important;\n  padding-bottom:\
          \ 0px !important;\n}\t\t  \n"
        title: $docker_title6$
        type: entities
      type: vertical-stack
    items_classes: col-xs-12 col-sm-4 col-sm-4 col-xl-4
    type: custom:dwains-flexbox-card
  items_classes: col-xs-12 col-md-12 col-lg-12 col-xl-12
  type: custom:dwains-flexbox-card
