blueprint:
  custom_cards:
  - mushroom-fan-card
  description: replaces fan card with mushroom fan card by Bourner
  name: Replace Mushroom Fan Card
  input:
    oscillate:
      type: checkbox
      description: Show Oscillate Control
    percentage:
      type: checkbox
      description: Show Percentage Control
    animation:
      type: checkbox
      description: Animate Icon when on
    state:
      type: checkbox
      description: Hide State
    collapsible:
      type: checkbox
      description: Colapse Controls when off  
  type: replace-card
  version: '1.1'
card:
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  show_oscillate_control: $oscillate$
  show_percentage_control: $percentage$
  icon_animation: $animation$
  hide_state: $state$
  collapsible_controls: $collapsible$
  type: custom:mushroom-fan-card
