blueprint:
  custom_cards:
  - mushroom-update-card
  description: replaces update card with mushroom update card by Bourner
  input:
    button:
      type: checkbox
      description: Show Button Controls
    picture:
      type: checkbox
      description: Use Picture Entity
    collapse:
      type: checkbox
      description: Collapse Controls when off    
  name: Replace Mushroom Update Card
  type: replace-card
  version: '1.2'
card:
  type: custom:mushroom-update-card
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  show_buttons_control: $button$
  use_entity_picture: $picture$
  collapsible_controls: $collapse$
