blueprint:
  custom_cards:
  - mushroom-light-card
  description: adds motion/window/door sensors with mushroom chip card by Bourner
  input:
    entity: 
      description: Choose entity
      type: entity-picker
      name: Entity
  name: Sensor Mushroom Chip Card
  type: card
  version: '1.0'
card:
  chips:
  - chip:
      content_info: name
      entity: $entity$
      type: entity
    conditions:
    - entity: $entity$
      state_not: 'off'
    type: conditional
  type: custom:mushroom-chips-card
